config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations",
    sessions: "sessions", omniauth_callbacks: "omniauth_callbacks"}
  mount Sidekiq::Web => "/sidekiq"

  scope "(:locale)", locale: /en|vn/ do
    root "documents#index"

    resources :users
    resources :categories
    resources :documents do
      resources :comments
    end
    resources :activites
    resources :favorites, only: [:create, :destroy]
    resources :downloads, only: :create
    resources :relationships, only: [:create, :destroy]
    resources :messages, only: [:index]
    resources :chatrooms
    resources :series
    resources :reviews
    resources :organizations do
      resources :admin_add_members, only: [:create, :destroy]
      resources :read_guide , only: [:create, :update, :destroy]
      resources :group_members do
        resources :admin_add_members, only: [:create, :destroy]
      end
      resources :documents
      resources :teams, except: [:index] do
        resources :admin_add_members, only: [:create, :destroy]
        resources :group_members, only: [:create, :destroy, :update] do
          resources :admin_add_members, only: [:create, :destroy]
        end
      end
    end
    resources :group_members, only: [:create, :destroy, :update]

    resources :shares
    mount ActionCable.server => "/cable"

    namespace :api do
      resources :documents, :users, :imageslides, :team_members, :team_requests,
        :organization_members, :organizations, :organization_documents, :teams, only: :index
    end

    namespace :admin do
      root "admins#index", as: :root
      resources :categories, :documents, :users, :statistic, :buycoins,
        :imageslides
    end

    resources :buycoins

    get "/:page", to: "static_pages#show"
  end
end

app/models/document.rb
class Document < ApplicationRecord
  acts_as_paranoid
  paginates_per Settings.users.per_page

  belongs_to :user
  belongs_to :category
  belongs_to :serie

  has_many :comments, dependent: :destroy
  has_many :reads, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :downloads, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :shares, dependent: :destroy, inverse_of: :document

  accepts_nested_attributes_for :shares, allow_destroy: true,
    reject_if: proc{|attributes| attributes[:share_id].blank?}

  mount_uploader :attachment, AttachmentUploader

  validates :name, presence: true, length: {maximum: Settings.document_length}

  enum status: [:waiting, :checked, :cancelled]
  enum status_upload: [:global, :shared, :individual]


  paginates_per Settings.document_per_page

  scope :in_category, ->category_id do
    where category_id: category_id if category_id.present?
  end

  scope :upload_count, ->date_time do
    where("date(created_at) = '#{date_time}'").count
  end

  def rate_average
    reviews.average(:rating).to_f if reviews.any?
  end

  class << self
    def own_documents user
      user.documents.checked.order(created_at: :desc)
        .limit(Settings.document.limit)
    end

    def newest
      Document.checked.where(status_upload: Document.status_uploads[:global]).order(
        created_at: :desc).limit(Settings.document.limit_1)
    end

    def get_read_document user
      document_ids = user.reads.pluck(:document_id)
      Document.where(id: document_ids).order(updated_at: :desc)
        .limit(Settings.document.limit_1)
    end

    def search params_search
      Document.where("name LIKE ?", "%#{params_search}%")
    end
  end
end

app/controllers/admin/documents_controller.rb
class Admin::DocumentsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!, :verify_admin
  load_and_authorize_resource

  def index
    @documents = Document.all.order(updated_at: :desc).page params[:page]
    @categories = Category.all
  end

  def update
    params[:status] = :checked
    if @document.update_attributes document_params
      flash[:success] = t ".update_success"
      @user = @document.user
      @user.update_attributes point: @user.point + Settings.coin_down
    else
      flash[:danger] = t ".update_error"
    end
    redirect_to admin_documents_path
  end

  def destroy
    if @document && @document.destroy
      flash[:success] = t ".destroy_success"
    else
      flash[:danger] = t ".destroy_error"
    end
    redirect_to admin_documents_path
  end

  private
  def document_params
    params.permit :status
  end
end

app/controllers/api/documents_controller.rb
class Api::DocumentsController < ApplicationController
  def index
    if params[:category_id].blank?
      @documents = Document.all.page params[:page]
    else
      category = Category.find_by id: params[:category_id]
      @documents = Document.where(category_id: category.id).page params[:page]
    end
    respond_to do |format|
      format.html do
        render partial: "admin/documents/documents",
        locals: {documents: @documents}
      end
    end
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!, except: :index
  load_and_authorize_resource
  load_resource :organization

  before_action only: :show do
    validate_permission_for_read_document @document
    validate_permission_for_document_status @document
  end

  def index
    @categories = Category.all
    @document_support = Supports::DocumentSupport.new
  end

  def new
    @document = Document.new
  end

  def create
    serie = Serie.create!(name: params[:series_name],
      organization_id: params[:organization_id], user_id: current_user.id) if
      params[:series_name].present?
    @document = current_user.documents.build document_params
    @document.serie_id = serie.id if serie.present?
    if @document.save
      if @organization.present?
        @organization.share_document @document
      end
      upload_document = UploadDocument.new @document, current_user
      Delayed::Job.enqueue upload_document, Settings.priority,
        Settings.time_delay.hours.from_now
      flash[:success] = t ".create_success"
      @organization.present? ? (redirect_to :back) : (redirect_to root_url)
    else
      render :new
    end
  end

  def update
    if params[:document][:shares_attributes].nil?
      flash[:warning] = t ".user_shared_cannot_blank"
    else
      shares_attributes = []
      if params[:share_team].present?
        convert_to_hash shares_attributes, Share.share_types[:team]
      else
        convert_to_hash shares_attributes, Share.share_types[:user]
      end
      if @document.update_attributes document_params
        flash[:success] = t ".share_success"
      else
        flash[:warning] = t ".share_failure"
      end
    end
    redirect_to :back
  end

  def destroy
    @user = @document.user
    if @document.destroy
      flash[:success] = t ".destroy_success"
    else
      flash[:danger] = t ".destroy_error"
    end
    redirect_to :back
  end

  def show
    @document_sp = Supports::DocumentSupport.new
    if current_user.present?
      @review = Review.find_by document_id: @document.id,
        user_id: current_user.id
      @review = current_user.reviews.build if @review.nil?
      @document.update_attributes view: @document.view + 1
      update_read @document
    end
  end

  private
  def document_params
    params.require(:document).permit :name, :description, :attachment,
      :category_id, :status_upload, :serie_id,
      shares_attributes: [:share_id, :share_type, :document_id]
  end

  def convert_to_hash shares_attributes, share_type
    params[:document][:shares_attributes].each do |user_id|
      shares_hash = Hash.new
      shares_hash[:share_id] = user_id
      shares_hash[:share_type] = share_type
      shares_attributes.push shares_hash
    end
    params[:document][:shares_attributes] = shares_attributes
  end

  def update_read document
    read = Read.find_by user_id: current_user.id, document_id: document.id
    if read.present?
      read.update_attributes read_count: read.read_count + 1
    else
      read = current_user.reads.build
      read.read_count = 1
      read.document = document
      read.save!
    end
  end
end

app/views/documents/_document.html.erb
<div class="col-xs-6 col-sm-3 col-md-3 col-lg-3">
  <div class="product">
    <div class="thumbnail">
      <div class="view-detail-product">
        <a href="#"><i class="fa fa-link"></i></a>
        <a href="<%= document_path(document) %>"><i class="fa fa-search"></i></a>
      </div>
      <% if document.attachment? %>
        <%= image_tag document.attachment.preview.url, class: "img-responsive" %>
      <% else %>
        <%= image_tag Settings.image, class: "img-responsive" %>
      <% end %>
      <div class="caption">
        <h3 class="product_name text-center"><%= document.name %></h3>
        <hr>
        <div class="row">
          <div class="col-md-6 text-left">
            <p>
              <i class="fa fa-calendar"></i>
              <span>
                <%= document.created_at.strftime(Settings.format_date) %>
              </span>
            </p>
            <p class="document-user-name">
              <i class="fa fa-share-square-o"></i>
              <span><%= document.user.name %></span>
            </p>
          </div>
          <div class="col-md-6 text-right">
            <p>
              <i class="fa fa-download"></i>
              <span><%= document.downloads.size %></span>
              <span><%= t ".downloads" %></span>
            </p>
            <p>
              <i class="fa fa-eye"></i>
              <span><%= document.reads.size %></span>
              <span><%= t ".views" %></span>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/documents/_favorite.html.erb
<%= form_for(current_user.favorites.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :document_id, @document.id %></div>
  <%= button_tag "", class: "btn btn-default button-2", id: "btn_favorite" do %>
    <i class="fa fa-gratipay"></i>
    <span><%= t ".like" %></span>
  <% end %>
<% end %>

app/views/documents/_favorite_form.html.erb
<div id="favorite_form">
  <% if @document_fav.nil? %>
    <%= render "favorite" %>
  <% else %>
    <%= render "unfavorite" %>
  <% end %>
</div>

app/views/documents/_form_review.html.erb
<div class="modal" id="mynewreview" tabindex="-1" role="dialog"
  aria-labelledby = "myModalLabel" aria-hidden = "true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"
          aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title mynewreview" id="myModalLabel"><%= @button %></h4>
      </div>
      <div id ="mynewreview1">
      <%= simple_form_for @review do |f| %>
        <div class="rating-content">
          <%= f.label :rating %>
          <% rate_size = @review.rating.to_i %>
          <% rate_size.times do |n| %>
            <%= image_tag(Settings.star_on, title: Settings.reivews[n],
              alt: "#{n+1}", class: "star-review") %>
          <% end %>
          <% (5-rate_size).times do |n| %>
            <%= image_tag(Settings.star_off, title: Settings.reivews[n],
              alt: "#{rate_size+n+1}", class: "star-review") %>
          <% end %>
          <%= f.hidden_field :id %>
          <%= f.hidden_field :rating %>
          <%= f.hidden_field :document_id, value: @document.id %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default"
            data-dismiss="modal" id="mynewcategoryclose">
            <%= t "title.close" %>
          </button>
          <%= f.submit @button, class: "btn btn-default", id: "review-btn" %>
        </div>
      <% end %>
    </div>
    </div>
  </div>
</div>

app/views/documents/_form_share.html.erb
<a class="btn btn-default btn-share-1" data-toggle="tooltip" title="<%= t "share" %>">
  <span class="fa fa-share-square-o"></span>
</a>
<div class="share-content-1">
  <%= form_for @document do |f| %>
    <%= hidden_field_tag :document_id, @document.id %>
    <%= f.hidden_field :status_upload, value: :shared %>
    <%= select_tag "document[shares_attributes]", options_for_select(
    load_user_will_be_shared_by_document(@document).map {|user| [user.name, user.id]}),multiple: true, size: Settings.size_share, class: "select-share-document"%>
  <%= f.submit t(".send"), class: "btn btn-default" %>
  <% end %>
</div>

app/views/documents/_unfavorite.html.erb
<%= form_for(current_user.favorites.find_by(document_id: @document.id),
  html: {method: :delete}, remote: true) do |f| %>
  <%= button_tag "", class: "btn btn-default button-2", id: "btn_unfavorite" do %>
    <i class="fa fa-thumbs-o-down"></i>
    <span><%= t ".dislike" %></span>
  <% end %>
<% end %>

app/views/documents/index.html.erb
<div class="header">
  <div class="container-fluid">
    <div class="img-back row-fluid">
      <div id="my_carousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#my_carousel" data-slide-to="0" class="active"></li>
          <li data-target="#my_carousel" data-slide-to="1"></li>
          <li data-target="#my_carousel" data-slide-to="2"></li>
          <li data-target="#my_carousel" data-slide-to="3"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <% if load_image.any? %>
            <% load_image.each do |image| %>
              <div class="item">
                <% if image.image.present? %>
                  <%= image_tag image.image.url, class: "img-responsive" %>
                <% else %>
                  <%= image_tag Setting.image, class: "img-responsive" %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
        <a class="left carousel-control" href="#my_carousel" role="button"
          data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only"><%= t ".previous" %></span>
        </a>
        <a class="right carousel-control" href="#my_carousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only"><%= t ".next" %></span>
        </a>
      </div>
    </div>
    <div class="contact">
      <p><%= t ".question" %>
        <i class="fa fa-phone"></i>
        <a href="#"><%= t ".phone" %></a>
        <i class="fa fa-envelope-o"></i>
        <a href="#"><%= t ".mail" %></a>
      </p>
    </div>
    <div class="header-info">
      <div class="row">
        <div class="col-md-5 col-md-offset-1 text-center">
          <h1>
            <span class="one-p"><%= t ".thoudrand" %></span>
            <span class="two-p"><%= t ".file" %></span>
          </h1>
          <h3><%= t ".know" %></h3>
          <a href="#" class="btn btn-default nut1"><%= t ".register" %></a>
        </div>
        <div class="col-md-5">
        </div>
      </div>
    </div>
  </div>
</div>
<div class="top2">
  <div class="container">
    <h2 class="text-center">
      <span><i class="fa fa-book letter"></i></span>
      <span class="letter"><%= t ".ni" %></span>
      <span class="letter"><%= t ".e" %></span>
      <span class="letter"><%= t ".w" %></span>
      <span class="letter"><%= t ".d" %></span>
      <span class="letter"><%= t ".o" %></span>
      <span class="letter"><%= t ".c" %></span>
      <span class="letter"><%= t ".u" %></span>
      <span class="letter"><%= t ".m" %></span>
      <span class="letter"><%= t ".e" %></span>
      <span class="letter"><%= t ".ni" %></span>
      <span class="letter"><%= t ".t" %></span>
      <span class="letter"><%= t ".s" %></span>
    </h2>
    <div class="row newest-product">
      <%= render @document_support.newest_documents(current_user) if
        @document_support.newest_documents(current_user).present? %>
    </div>
    <% if user_signed_in? && @document_support.read_documents(current_user).present? %>
      <h2 class="text-center">
        <span class="letter"><i class="fa fa-bookmark"></i></span>
        <span class="letter"><%= t ".r" %></span>
        <span class="letter"><%= t ".e" %></span>
        <span class="letter"><%= t ".a" %></span>
        <span class="letter"><%= t ".d" %></span>
        <span class="letter"><%= t ".d" %></span>
        <span class="letter"><%= t ".o" %></span>
        <span class="letter"><%= t ".c" %></span>
        <span class="letter"><%= t ".u" %></span>
        <span class="letter"><%= t ".m" %></span>
        <span class="letter"><%= t ".e" %></span>
        <span class="letter"><%= t ".ni" %></span>
        <span class="letter"><%= t ".t" %></span>
        <span class="letter"><%= t ".s" %></span>
      </h2>
      <div class="row best-product">
        <%= render @document_support.read_documents(current_user) %>
      </div>
    <% end %>
  </div>
</div>

app/views/documents/new.html.erb
<h2 class="tittle text-center"><%= t ".upload_file" %></h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @document, html: {multipart: true} do |f| %>
    <%= render "shared/error_messages", object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", required: "true",
        maxlength: Settings.document_length %>
      <%= f.label :description %>
      <%= f.text_area :description, placeholder:
        t(".compose_description"), class: "form-control", rows: Settings.rows %>
      <div class="row">
        <div class="col-md-12">
          <%= f.label :attachment %>
          <%= f.file_field :attachment %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 category_doc_upload">
        <p><%= t ".category" %></p>
          <%= f.select :category_id, options_for_select(load_categories.collect{
            |category| [category.name, category.id]}),
            {class: "btn btn-default", include_blank: t(".all")} %>
        </div>
        <div class="col-md-6 serie_doc_upload">
          <p>
            <b id="series-current"><%= t ".series" %></b>
            <a id="create-series"><%= t ".create_serie" %></a>
          </p>
          <div id="create-series-area">
            <input type="text" name="series_name" class="form-control">
          </div>
          <div id="choose-series">
            <%= f.select :serie_id, options_for_select(load_series(current_user).collect{
              |serie| [serie.name, serie.id]}),
              {class: "btn btn-default", include_blank: t(".all")} %>
          </div>
        </div>
      </div>
      <div class="row status_upload">
        <div class="col-md-12">
          <% Document.status_uploads.keys.each do |status| %>
            <%= f.radio_button :status_upload, status,
            checked: status == Settings.value_global %>
            <%= f.label :status_upload, status, value: status %>
          <% end %>
        </div>
      </div>
      <%= f.submit t(".upload"), class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/documents/show.html.erb
<div class="view-document col-md-9 text-center">
  <div class="row">
  <div class="col-md-4">
    <h2 class="text-center"><%= @document.name %></h2>
  </div>
  <div class="col-md-8 text-left">
    <span>
      <%= social_share_button_tag(@document.name) %>
    </span>
  </div>
  </div>
  <div class="row view-two">
    <div class="col-md-8 text-left">
      <p class="author_info">
        <span><%= t ".share_by" %></span>
        <span class="user_name">
          <%= link_to @document.user.name, @document.user %>
        </span>
        <span><%= t ".dash" %></span>
        <span><%= t ".date" %></span>
        <span class="document_date">
          <%= @document.created_at.strftime(Settings.format_date) %>
        </span>
        <span><%= t ".dash" %></span>
        <span class="document_size"><%= @document.user.documents.size %></span>
        <span><%= t ".documents" %></span>
      </p>
      <div class="row">
        <div class="col-md-3">
          <p class="favorite_document">
            <span>
              <%= render "favorite_form" if user_signed_in? %>
            </span>
          </p>
        </div>
        <div class="col-md-9">
          <p class="text-left">
            <span class="fav-count pull-left" id="fav_count">
              <%= @document.favorites.count %>
            </span>
          </p>
          <% if user_signed_in? %>
            <% @download_free = @document_sp.get_download_free(current_user) %>
            <% if @document.user == current_user %>
              <%= form_for current_user.downloads.build do |f| %>
                <%= f.hidden_field :document_id, value: @document.id %>
                <%= f.hidden_field :count_download, value: @download_free %>
                <%= button_tag "", class: "btn btn-default button-2",
                  id: "btn_download" do %>
                  <i class="fa fa-download"></i>
                  <span><%= t ".download" %></span>
                <% end %>
              <% end %>
            <% else %>
              <% if @download_free < Settings.count_free_download %>
                <%= form_for current_user.downloads.build do |f| %>
                  <%= f.hidden_field :document_id, value: @document.id %>
                  <%= f.hidden_field :count_download, value: @download_free %>
                  <%= button_tag "", class: "btn btn-default button-2",
                    id: "btn_download" do %>
                    <i class="fa fa-download"></i>
                    <span><%= t ".download" %></span>
                  <% end %>
                <% end %>
              <% else %>
                <% if current_user.point >= Settings.coin_down %>
                  <%= form_for current_user.downloads.build do |f| %>
                    <%= f.hidden_field :document_id, value: @document.id %>
                    <%= f.hidden_field :count_download, value: @download_free %>
                    <%= button_tag "", class: "btn btn-default button-2",
                      id: "btn_download" do %>
                      <i class="fa fa-download"></i>
                      <span><%= t ".download" %></span>
                    <% end %>
                  <% end %>
                <% else %>
                  <p class="not_enought_coin">
                    <%= t ".please_click_1" %>
                    <%= link_to t(".here"), new_buycoin_path %><%= t ".to_buycoin" %>
                  </p>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
          <% if @document.user == current_user %>
            <%= link_to document_path(@document), method: :delete,
              class: "btn btn-default delete-doc", data: {confirm: t(".delete_confirm")} do %>
              <span class="fa fa-trash-o"></span>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-4 text-center benphai">
      <div class="row">
        <div class="col-md-6">
          <p class="views_count" id="download_count">
          <% if user_signed_in? %>
            <% if @download_free >= Settings.count_free_download %>
              <%= Settings.coin_when_nonfree %>
            <% else %>
              <%= Settings.coin_when_free %>
            <% end %>
          <% else %>
            <%= Settings.coin_when_free %>
          <% end %>
          </p>
          <p><%= t ".coins" %></p>
        </div>
        <div class="col-md-6">
          <p class="views_count"><%= @document.view %></p>
          <p><%= t ".views" %></p>
        </div>
      </div>
    </div>
  </div>
  <% if @document.attachment.url.blank? %>
    <h2><%= t ".document_blank" %></h2>
  <% else %>
    <iframe src="<%= @document.attachment.url %>" style="width:800px; height:700px;" frameborder="0" id="iframe">
    </iframe>
  <% end %>
  <hr>
  <p class="tags">
    <% load_categories.each do |category| %>
      <i class="fa fa-tags"></i>
      <span><%= link_to category.name, category_path(category) %></span>
    <% end %>
  </p>
  <hr>
  <div class="tab-content">
    <div id="comment">
      <h3 class="tittle-comment text-left">
        <i class="fa fa-comments-o"></i><%= t ".comment" %>
        <%= t ".open" %><span class="comment-count"><%= @document.comments.count %></span><%= t ".close" %>
      </h3>
      <% if user_signed_in? %>
        <span class="header-comment pull-left">
          <%= t ".write_your_comment" %>
        </span>
        <div class="form-group">
          <%= form_for [@document, @document.comments.new], remote: true do |f| %>
            <%= f.text_area :content, class: "form-control",
              placeholder: t(".compose_new_comment"), class: "form-control",
              rows: Settings.rows, required: true %>
            <%= f.submit t(".submit"), class: "btn btn-default btn_comment pull-right",
              id: "comment-btn" %>
          <% end %>
        </div>
      <% else %>
        <%= t ".please_click" %>
        <%= link_to t(".here"), new_user_session_path %><%= t ".to_login" %>
      <% end %>
      <div class="list-comment">
        <ul id="comments">
          <%= render @document_sp.list_comments @document %>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="col-md-3">
  <div class="row review-document">
    <div class="header-review">
      <h3 class="text-left rss">
        <i class="fa fa-rss"></i><%= t ".review" %>
      </h3>
      <% if @document.rate_average.present? %>
        <% rate_average = @document.rate_average.round(Settings.round) %>
      <% else %>
        <% rate_average = 0 %>
      <% end %>
      <div class="star_rewview_document <%= t "hidden" if rate_average.nil? %>">
        <h3>
          <span><%= t "documents.star" %></span>
          <strong id="star_rewview_document" class="stat">
            <% if rate_average.present? %>
              <%= rate_average %>
            <% end %>
          </strong>
          <i class="fa fa-star-o"></i>
        </h3>
        <p class="notice_review"><%= t ".please_give_me_your_review" %></p>
        <p>
          <% if @review.present? %>
            <% if @review.id.nil? %>
              <% @button = t("documents.add_review") %>
            <% else %>
              <% @button = t("documents.update_review") %>
            <% end %>
          <% end %>
          <div id="button_create" class="btn-review-1">
            <a type="button" class="btn btn-default mynewreview pull-right"
              data-toggle="modal" data-target="#mynewreview"
              ><%= @button %></a>
          </div>
        </p>
      </div>
    </div>
    <div class="reviews-index">
      <% @document_sp.list_reviews(@document).each do |review| %>
        <%= render partial: "reviews/review", object: review %>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <%= render "form_review" %>
    <% end %>
  </div>
  <div class="row">
    <% if user_signed_in? && @document.user == current_user %>
      <%= render "form_share" %>
    <% end %>
  </div>
  <% if @document.serie %>
    <ul class="list-group">
      <h3><%= link_to @document.serie.name, @document.serie %></h3>
      <% @document_sp.load_documents_in_series(@document).each do |document| %>
        <li class="docs-serie">
          <h4>
            <% if @document.id == document.id %>
              <%= link_to document.name, document, class: "docs-serie" %>
            <% else %>
              <%= link_to document.name, document %>
            <% end %>
          </h4>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>