config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations",
    sessions: "sessions", omniauth_callbacks: "omniauth_callbacks"}
  mount Sidekiq::Web => "/sidekiq"

  scope "(:locale)", locale: /en|vn/ do
    root "documents#index"

    resources :users
    resources :categories
    resources :documents do
      resources :comments
    end
    resources :activites
    resources :favorites, only: [:create, :destroy]
    resources :downloads, only: :create
    resources :relationships, only: [:create, :destroy]
    resources :messages, only: [:index]
    resources :chatrooms
    resources :series
    resources :reviews
    resources :organizations do
      resources :admin_add_members, only: [:create, :destroy]
      resources :read_guide , only: [:create, :update, :destroy]
      resources :group_members do
        resources :admin_add_members, only: [:create, :destroy]
      end
      resources :documents
      resources :teams, except: [:index] do
        resources :admin_add_members, only: [:create, :destroy]
        resources :group_members, only: [:create, :destroy, :update] do
          resources :admin_add_members, only: [:create, :destroy]
        end
      end
    end
    resources :group_members, only: [:create, :destroy, :update]

    resources :shares
    mount ActionCable.server => "/cable"

    namespace :api do
      resources :documents, :users, :imageslides, :team_members, :team_requests,
        :organization_members, :organizations, :organization_documents, :teams, only: :index
    end

    namespace :admin do
      root "admins#index", as: :root
      resources :categories, :documents, :users, :statistic, :buycoins,
        :imageslides
    end

    resources :buycoins

    get "/:page", to: "static_pages#show"
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :teams, dependent: :destroy
  has_many :group_members, foreign_key: :group_id, dependent: :destroy
  has_many :read_guides, dependent: :destroy
  has_many :series, foreign_key: :organization_id, class_name: Serie.name

  accepts_nested_attributes_for :group_members
  mount_uploader :picture, OrganizationPictureUploader
  validates :name, presence: true, length: {maximum: Settings.organization.name.max_length}
  validate :picture_size

  def members
    GroupMember.where group_id: self.id, group_type: GroupMember.group_types[:organization]
  end

  def create_organization_owner user
    GroupMember.create!(user_id: user.id,
      group_id: self.id,
      group_type: GroupMember.group_types[:organization],
      role: GroupMember.roles[:admin],
      confirm: true)
  end

  def add_member user
    GroupMember.create!(
      user_id: user.id,
      group_id: self.id,
      group_type: GroupMember.group_types[:organization],
      role: GroupMember.roles[:member],
      confirm: true)
  end

  def share_document document
    Share.create!( share_id: self.id,
      share_type: Share.share_types[:organization],
      document_id: document.id
      )
  end

  def has_member? user
    GroupMember.organization_user.member.find_by user_id: user.id, group_id: self.id
  end

  def has_admin? user
    GroupMember.organization_user.admin.find_by user_id: user.id, group_id: self.id
  end

  def picture_size
    if picture.size > Settings.organization.picture.max_size.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end

  def document_ids
      Share.select(:document_id).where(share_type: Share.share_types[:organization],
        share_id: self.id)
    end

  class << self
    def search params_search
      Organization.where("name LIKE ?", "%#{params_search}%")
    end

    def find_members group_id, user_name, confirm
      users = User.search(user_name)
      GroupMember.where group_id: group_id, group_type: GroupMember.group_types[:organization],
        user_id: users.ids, confirm: confirm
    end
  end
end

app/controllers/api/organizations_controller.rb
class Api::OrganizationsController < ApplicationController
  def index
    @organizations = params[:org_name].present? ?
      Organization.search(params[:org_name]) : Organization.all
    respond_to do |format|
      format.html do
        render partial: "organizations/organizations",
        locals: {organizations: @organizations}
      end
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :authenticate_user!, except: :index
  load_and_authorize_resource

  def index
    @organizations = Organization.all.page(params[:page])
      .per Settings.organs_per_page
    @organization = Organization.new
  end

  def show
    @member = @organization.members.find_by user_id: current_user.id
    @support = Supports::OrganizationSupport.new @organization
    if params[:tab_id].present?
      show_tab @support
    end
  end

  def create
    @organization = Organization.new organization_params
    if @organization.save
      @organization.create_organization_owner current_user
      flash[:success] = t ".organization_was_added"
      redirect_to @organization
    else
      render :new
    end
  end

  def update
    if @organization.has_admin? current_user
      if params[:guide_id].present?
        @organization.update_attributes guide_id: params[:guide_id]
        flash[:success] = t ".organization_was_edited"
        redirect_to :back
      else
        if @organization.update_attributes organization_params
          flash[:success] = t ".organization_was_edited"
          redirect_to @organization
        else
          flash[:danger] = t ".can_not_edit"
          render :edit
        end
      end
    else
      flash[:danger] = t ".do_not_have_permission!"
      redirect_to @organization
    end
  end

  def destroy
    if @organization.has_admin? current_user
      if @organization.destroy
        flash[:success] = t ".organization_was_deleted"
        redirect_to organizations_path
      else
        flash[:danger] = t ".can_not_delete"
        redirect_to @organization
      end
    else
      flash[:danger] = t ".do_not_have_permission!"
      redirect_to @organization
    end
  end

  private

  def organization_params
    params.require(:organization).permit :name, :picture, :description,
      group_member_attributes: [:user_id, :group_id, :group_type, :role, :confirm]
  end

  def show_tab support
    case params[:tab_id]
    when "members"
      members = support.members
    when "requests"
      members = support.requests
    end
    respond_to do |format|
      format.html do
        render partial: "organizations/show_tpl/members",
          locals: {group_members: members}
      end
    end
  end

end

app/views/organizations/_join_request.html.erb
<div id="organization-request">
  <div id="leave-organization-request">
    <% if @member.present? %>
      <%= render partial: "shared/leave", locals: {member: @member} %>
    <% end %>
  </div>
  <div id="join-organization-request">
    <% if !@member.present? %>
      <%= render partial: "shared/join", locals: {object: @organization} %>
    <% end %>
  </div>
</div>

app/views/organizations/_new.html.erb
<div class="organization-sidebar">
  <div class="add-organization-sidebar">
    <h2 class="sidebar-item-title"><%= t ".add_organization" %></h2>
    <%= form_for @organization do |f| %>
      <%= f.label :picture %>
      <%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png",
       class: "btn-choose-picture" %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>

      <%= f.submit (t ".add_organization"), class: "btn btn-default",
        id: "btn-add-organization" %>
    <% end %>
  </div>
</div>

app/views/organizations/_organizations.html.erb
<div id="list-organizations">
  <% organizations.each do |organization| %>
    <li>
      <%= link_to organization, class: "organization-item" do %>
        <div class="col-md-3 col-sm-3 col-xs-12 organization-picture">
          <%= image_tag organization.picture.url, class: "" %>
        </div>
        <div class="col-md-9 col-sm-9 col-xs-12 organization-detail">
          <h3 class="organization-name"><%= organization.name %></h3>
          <p class="number-of-member"><%=
            GroupMember.group_member(organization.class.name.downcase,
              organization.id).length %> <%= t "organizations.members" %></p>
          <p class="description"><%= truncate organization.description,
            length: Settings.organization.description_size %></p>
        </div>
      <% end %>
    </li>
  <% end %>
</div>

app/views/organizations/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 group-form">
    <div class="outer-title">
      <h1 class="title"><%= t "organizations.edit_organization" %> <%= @organization.name %></h1>
      <%= link_to @organization, method: :delete,
        data: {confirm: (t ".are_you_sure")} do %>
        <i class="fa fa-trash icon-delete" aria-hidden="true" title="<%= t "delete" %>"></i>
      <% end %>
    </div>
    <%= form_for @organization do |f| %>
      <%= f.label :picture %>
      <%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png",
        class: "btn-choose-picture" %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>

      <%= f.submit (t "save"), class: "btn btn-primary btn-edit",
        id: "btn-add-organization" %>
    <% end %>
  </div>
</div>

app/views/organizations/index.html.erb
<div class="container organization-page">
  <h1 class="header-page-title"><%= t "organizations.organizations" %></h1>
  <%= text_field_tag :search, params[:search], class: "form-control input-lg",
    id: "search_organization_ajax" %>
  <div class="col-md-8 col-sm-8 col-xs-12 row">
    <ul id="table-organizations" class="list-organizations">
      <%= render partial: "organizations", locals: {organizations: @organizations} %>
    </ul>
  </div>
  <div class="col-md-4 col-sm-4 col-xs-12 row">
    <%= render "organizations/new", locals: {organization: @organization} %>
  </div>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <%= paginate @organizations %>
    </div>
  </div>
</div>

app/views/organizations/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @organization do |f| %>
      <%= f.label :picture %>
      <%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png",
        class: "btn-choose-picture" %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>

      <%= f.submit (t ".add_organization"), class: "btn btn-default",
        id: "btn-add-organization" %>
    <% end %>
  </div>
</div>

app/views/organizations/show.html.erb
<div class="organization-page">
  <div class="left-sidebar col-md-2 col-sm-2">
    <div class="page-title">
      <% if @organization.has_admin?(current_user) %>
        <%= link_to edit_organization_path, class: "btn-edit" do %>
          <h1 class="title">
            <%= @organization.name %>
          </h1>
          <i class="fa fa-pencil" aria-hidden="true"></i>
        <% end %>
      <% else %>
        <h1 class="title">
          <%= @organization.name %>
        </h1>
      <% end %>
    </div>
    <div class="action">
      <%= render "join_request" %>
    </div>
    <% if @organization.has_member? current_user %>
      <% if @support.read_guide(current_user).present? %>
        <%= hidden_field_tag :id, @support.read_guide(current_user).id,
          id: "read_setting_guide" %>
      <% end %>
      <ul class="nav nav-tabs list-group" id="tabs">
        <li class="active">
          <a id="documents-tab" data-destination-id="documents" data-toggle="tab"
             href="#documents"><%= t "organizations.show.documents" %></a>
        </li>
        <li>
          <a data-toggle="modal" data-target="#my-Guide" class="guide-modal">
            <%= t ".guide" %>
          </a>
          <%= render "organizations/show_tpl/guide" %>
        </li>
        <li>
          <a id="teams-tab" data-destination-id="teams" data-toggle="tab"
             href="#teams"><%= t "organizations.show.teams" %></a>
        </li>
        <li class="tab-ajax">
          <a id="members-tab" data-destination-id="members" data-toggle="tab"
             href="#members"><%= t "organizations.show.members" %></a>
        </li>
        <% if @organization.has_admin? current_user %>
          <li class="tab-ajax">
            <a id="requests-tab" data-destination-id="requests" data-toggle="tab"
               href="#requests"><%= t "organizations.show.requests" %></a>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <% if @organization.has_member? current_user %>
    <div class="tab-content col-md-8 col-sm-8">
      <div id="documents" class="tab-pane fade in active documents">
        <div id="table-document">
          <%= text_field_tag :search, params[:search], class: "form-control input-lg",
            id: "search_organization_document_ajax", placeholder: (t "organizations.search") %>
          <%= hidden_field_tag :id, params[:page], id: "search_params_id" %>
          <%= render partial: "organizations/show_tpl/documents",
            locals: {documents: @support.documents,
              organization: @organization} %>
        </div>
      </div>
      <div id="teams" class="tab-pane fade teams">
        <%= text_field_tag :search, params[:search], class: "form-control input-lg",
          id: "search_team_ajax", placeholder: (t "organizations.search") %>
        <%= hidden_field_tag :id, @organization.id, id: "search_organization_id" %>
        <div id="table-teams">
          <%= render partial: "organizations/show_tpl/teams",
            locals: {organization: @organization, teams: @support.teams}  %>
        </div>
      </div>
      <div id="members" class="tab-pane fade members" data-confirm="true"></div>
      <% if @organization.has_admin? current_user %>
        <div id="requests" class="tab-pane fade requests" data-confirm="false"></div>
      <% end %>
    </div>
    <% if @organization.has_admin? current_user %>
      <div class="right-sidebar col-md-2 col-sm-2">
        <div class="upload">
          <button type="button" class="btn btn-upload" data-toggle="modal"
            data-target="#upload-modal">
            <i class="fa fa-plus" aria-hidden="true"></i>
            <%= t "upload" %>
          </button>
        </div>
        <%= render "organizations/show_tpl/upload" %>
        <label><%= t ".add_member" %></label>
        <%= select_tag "organization-select-user", options_for_select(
          user_not_in_organization(@organization).map {
            |user| [user.name, user.id] }),
              multiple: true, size: Settings.organization.select_box_size,
              class: "select-user-to-add", include_blank: true %>
        <button id="add-organization-member-btn" class="btn btn-default"
          data-group-id="<%= @organization.id %>"
          data-group-type="<%= @organization.class.name.downcase %>">
          <%= t ".add_member" %>
        </button>
      </div>
    <% end %>
  <% end %>
</div>