config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations",
    sessions: "sessions", omniauth_callbacks: "omniauth_callbacks"}
  mount Sidekiq::Web => "/sidekiq"

  scope "(:locale)", locale: /en|vn/ do
    root "documents#index"

    resources :users
    resources :categories
    resources :documents do
      resources :comments
    end
    resources :activites
    resources :favorites, only: [:create, :destroy]
    resources :downloads, only: :create
    resources :relationships, only: [:create, :destroy]
    resources :messages, only: [:index]
    resources :chatrooms
    resources :series
    resources :reviews
    resources :organizations do
      resources :admin_add_members, only: [:create, :destroy]
      resources :read_guide , only: [:create, :update, :destroy]
      resources :group_members do
        resources :admin_add_members, only: [:create, :destroy]
      end
      resources :documents
      resources :teams, except: [:index] do
        resources :admin_add_members, only: [:create, :destroy]
        resources :group_members, only: [:create, :destroy, :update] do
          resources :admin_add_members, only: [:create, :destroy]
        end
      end
    end
    resources :group_members, only: [:create, :destroy, :update]

    resources :shares
    mount ActionCable.server => "/cable"

    namespace :api do
      resources :documents, :users, :imageslides, :team_members, :team_requests,
        :organization_members, :organizations, :organization_documents, :teams, only: :index
    end

    namespace :admin do
      root "admins#index", as: :root
      resources :categories, :documents, :users, :statistic, :buycoins,
        :imageslides
    end

    resources :buycoins

    get "/:page", to: "static_pages#show"
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :teams, dependent: :destroy
  has_many :group_members, foreign_key: :group_id, dependent: :destroy
  has_many :read_guides, dependent: :destroy
  has_many :series, foreign_key: :organization_id, class_name: Serie.name

  accepts_nested_attributes_for :group_members
  mount_uploader :picture, OrganizationPictureUploader
  validates :name, presence: true, length: {maximum: Settings.organization.name.max_length}
  validate :picture_size

  def members
    GroupMember.where group_id: self.id, group_type: GroupMember.group_types[:organization]
  end

  def create_organization_owner user
    GroupMember.create!(user_id: user.id,
      group_id: self.id,
      group_type: GroupMember.group_types[:organization],
      role: GroupMember.roles[:admin],
      confirm: true)
  end

  def add_member user
    GroupMember.create!(
      user_id: user.id,
      group_id: self.id,
      group_type: GroupMember.group_types[:organization],
      role: GroupMember.roles[:member],
      confirm: true)
  end

  def share_document document
    Share.create!( share_id: self.id,
      share_type: Share.share_types[:organization],
      document_id: document.id
      )
  end

  def has_member? user
    GroupMember.organization_user.member.find_by user_id: user.id, group_id: self.id
  end

  def has_admin? user
    GroupMember.organization_user.admin.find_by user_id: user.id, group_id: self.id
  end

  def picture_size
    if picture.size > Settings.organization.picture.max_size.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end

  def document_ids
      Share.select(:document_id).where(share_type: Share.share_types[:organization],
        share_id: self.id)
    end

  class << self
    def search params_search
      Organization.where("name LIKE ?", "%#{params_search}%")
    end

    def find_members group_id, user_name, confirm
      users = User.search(user_name)
      GroupMember.where group_id: group_id, group_type: GroupMember.group_types[:organization],
        user_id: users.ids, confirm: confirm
    end
  end
end

app/controllers/api/organizations_controller.rb
class Api::OrganizationsController < ApplicationController
  def index
    @organizations = params[:org_name].present? ?
      Organization.search(params[:org_name]) : Organization.all
    respond_to do |format|
      format.html do
        render partial: "organizations/organizations",
        locals: {organizations: @organizations}
      end
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :authenticate_user!, except: :index
  load_and_authorize_resource

  def index
    @organizations = Organization.all.page(params[:page])
      .per Settings.organs_per_page
    @organization = Organization.new
  end

  def show
    @member = @organization.members.find_by user_id: current_user.id
    @support = Supports::OrganizationSupport.new @organization
    if params[:tab_id].present?
      show_tab @support
    end
  end

  def create
    @organization = Organization.new organization_params
    if @organization.save
      @organization.create_organization_owner current_user
      flash[:success] = t ".organization_was_added"
      redirect_to @organization
    else
      render :new
    end
  end

  def update
    if @organization.has_admin? current_user
      if params[:guide_id].present?
        @organization.update_attributes guide_id: params[:guide_id]
        flash[:success] = t ".organization_was_edited"
        redirect_to :back
      else
        if @organization.update_attributes organization_params
          flash[:success] = t ".organization_was_edited"
          redirect_to @organization
        else
          flash[:danger] = t ".can_not_edit"
          render :edit
        end
      end
    else
      flash[:danger] = t ".do_not_have_permission!"
      redirect_to @organization
    end
  end

  def destroy
    if @organization.has_admin? current_user
      if @organization.destroy
        flash[:success] = t ".organization_was_deleted"
        redirect_to organizations_path
      else
        flash[:danger] = t ".can_not_delete"
        redirect_to @organization
      end
    else
      flash[:danger] = t ".do_not_have_permission!"
      redirect_to @organization
    end
  end

  private

  def organization_params
    params.require(:organization).permit :name, :picture, :description,
      group_member_attributes: [:user_id, :group_id, :group_type, :role, :confirm]
  end

  def show_tab support
    case params[:tab_id]
    when "members"
      members = support.members
    when "requests"
      members = support.requests
    end
    respond_to do |format|
      format.html do
        render partial: "organizations/show_tpl/members",
          locals: {group_members: members}
      end
    end
  end

end

app/views/organizations/show_tpl/_default.html.erb
<h3><%= t "organizations.show.default" %></h3>

app/views/organizations/show_tpl/_documents.html.erb
<div id="list-documents">
  <% if documents.any? %>
    <% documents.each do |document| %>
      <div class="document-user">
        <div class="col-md-8 col-sm-8 col-xs-8">
          <div class="row">
            <div class="col-md-4" id="image_document">
              <a href="<%= document_path(document) %>">
                <% if document.attachment? %>
                  <%= image_tag document.attachment.preview.url, class: "img-responsive" %>
                <% else %>
                  <%= image_tag Settings.image, class: "img-responsive" %>
                <% end %>
              </a>
            </div>
            <div class="col-md-8">
              <% if document.checked? %>
                <h4>
                  <%= link_to document.name, document_path(document) %>
                </h4>
              <% else %>
                <h4><%= document.name %></h4>
              <% end %>
              <p>
                <i class="fa fa-tag">
                  <span>
                    <%= link_to document.category.name,
                      category_path(document.category) if document.category.present? %>
                  </span>
                  <span class="time">
                      <%= document.created_at.strftime(Settings.format_date) %>
                    </span>
                </i>
              </p>
              <p><%= truncate document.description, length: Settings.organization.description_size %></p>
              <p>
                <% load_categories.each do |category| %>
                  <i class="fa fa-tags"></i>
                  <span><%= link_to category.name, category_path(category) %></span>
                <% end %>
              </p>
              <% if organization.has_admin?(current_user) &&
                organization.guide_id != document.id %>
                <%= form_for @organization do |f| %>
                  <%= hidden_field_tag :guide_id, document.id %>
                  <%= f.submit t(".assign_guide"), class: "btn btn-default" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <div>
          <% if document.user == current_user || organization.has_admin?(current_user) %>
            <div class="col-md-4 col-sm-4 col-xs-4 setting">
              <button class="btn setting-bars-btn" type="button" data-toggle="dropdown">
                <i class="fa fa-bars" aria-hidden="true"></i>
              </button>
              <ul class="dropdown-menu dropdown-menu-right setting-bars">
                <li>
                  <a class="btn-share" id="<%= document.id %>" data-toggle="modal" data-target="#document_detail_<%= document.id %>">
                    <span class="fa fa-share-square-o"><%= t ".share_member" %></span>
                  </a>
                </li>
                <li>
                  <a class="btn-share-team" id="<%= document.id %>" data-toggle="modal" data-target="#share_team_detail_<%= document.id %>">
                    <span class="fa fa-share-square-o"><%= t ".share_team" %></span>
                  </a>
                </li>
                <% unless organization.guide_id == document.id %>
                  <li>
                    <%= link_to document_path(document), method: :delete,
                      class: "", data: {confirm: t(".delete_confirm")} do %>
                      <span class="fa fa-trash-o"><%= t "organizations.show.delete" %></span>
                    <% end %>
                  </li>
                <% end %>
              </ul>
              <div class="share-member modal" id="document_detail_<%= document.id %>">
                <div class="modal-dialog">
                  <!-- Modal content-->
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title">Share to member</h4>
                    </div>
                    <%= form_for document do |f| %>
                      <%= hidden_field_tag :document_id, document.id %>
                      <%= f.hidden_field :status_upload, value: :shared %>

                      <%= f.label :select_member %>
                      <%= select_tag "document[shares_attributes]", options_for_select(
                        load_user_will_share_document(document, organization).map { |user|
                          [user.name, user.id] }), multiple: true,
                            size: Settings.size_share, class: "select-share-document" %>
                      <div class="btn-share">
                        <%= f.submit t(".send"), class: "btn btn-default btn-share" %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="share-team modal" id="share_team_detail_<%= document.id %>">
                <div class="modal-dialog">
                  <!-- Modal content-->
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title">Share to team</h4>
                    </div>
                    <%= form_for document do |f| %>
                      <%= hidden_field_tag :document_id, document.id %>
                      <%= f.hidden_field :status_upload, value: :shared %>

                      <%= f.label :select_team %>
                      <%= select_tag "document[shares_attributes]", options_for_select(
                        load_team_will_share_document(document, organization).map { |team|
                          [team.name, team.id] }), multiple: true,
                            size: Settings.size_share, class: "select-share-team" %>
                      <div class="btn-share">
                        <%= f.submit t(".send"), class: "btn btn-default " %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/organizations/show_tpl/_guide.html.erb
<div id="my-Guide" class="modal" role="dialog">
  <% if @organization.guide_id.nil? %>
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"><%= t "organization.show.guide" %></h4>
        </div>
        <div class="modal-body">
          <p><%= t "none" %></p>
        </div>
        <div class="modal-footer">
          <% if @support.read_guide(current_user).present? %>
            <div class="close_guide">
              <button type="button" class="btn btn-default btn-lg" data-dismiss="modal">
                <%= t "agree" %>
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% else %>
    <% if @support.guide.attachment.url.blank? %>
      <h2><%= t ".document_blank" %></h2>
    <% else %>
      <div id="embed_guide">
        <embed src="<%= @support.guide.attachment.url %>"
          style="width:100%; height:100%;" frameborder="0" id="show_guide" >
      </div>
    <% end %>
  <% end %>
  <% if @support.read_guide(current_user).present? %>
    <div class="close_guide">
      <button type="button" class="btn btn-default btn-lg" data-dismiss="modal">
        <%= t "agree" %>
      </button>
    </div>
  <% end %>
</div>

app/views/organizations/show_tpl/_member.html.erb
<table class="table table-hover">
  <thead>
  <th><%= t "organizations.team.index" %></th>
  <th><%= t "organizations.show.name" %></th>
  <th><%= t "organizations.show.email" %></th>
  <% if organization.has_admin?(current_user) %>
    <th><%= t "organizations.show.assign_admin" %></th>
    <th><%= t "organizations.show.action" %></th>
  <% end %>
  </thead>
  <tbody>
  <% group_members.each_with_index do |member, index| %>
    <tr id="accept-request-<%= member.id %>">
      <td><%= index + 1 %></td>
      <td>
        <%= member.name %>
        <%= hidden_field_tag :user_id, member.user_id, id: "find_user_id" %>
      </td>
      <td><%= member.email %></td>
      <% if organization.has_admin?(current_user) %>
        <td>
          <% if member.role == "member" && member.confirm %>
            <button data-id="<%= member.id %>" data-action="admin"
              class="btn btn-default btn-organization-assign">
              <i class="fa fa-check" aria-hidden="true"></i>
            </button>
          <% end %>
        </td>

        <td>
          <% if member.confirm? %>
            <% if member.role != "admin" %>
              <button data-id="<%= member.id %>"
                class="btn btn-default btn-organization-decline">
                <i class="fa fa-ban" aria-hidden="true"></i>
              </button>
            <% end %>
          <% else %>
            <button data-id="<%= member.id %>" data-action="true"
              class="btn btn-default btn-organization-accept">
              <i class="fa fa-check" aria-hidden="true"></i>
            </button>
            <button data-id="<%= member.id %>" class="btn btn-default btn-organization-decline">
              <i class="fa fa-ban" aria-hidden="true"></i>
            </button>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/organizations/show_tpl/_members.html.erb
<%= text_field_tag :search, params[:search], class: "form-control input-lg",
  id: "search_organization_member_ajax", placeholder: (t "organizations.search") %>
<%= hidden_field_tag :organization_id, @organization.id, id: "search_organization_id" %>
<div class="list-members">
  <%= render partial: "organizations/show_tpl/member",
    locals: {group_members: group_members, organization: @organization} %>
</div>

app/views/organizations/show_tpl/_teams.html.erb
<div id="list-teams">
  <h3><%= t ".teams" %></h3>
  <table class="table table-hover ">
    <thead>
      <tr>
        <th class="col-md-2"><%= t ".index" %></th>
        <th class="col-md-3"><%= t ".name" %></th>
        <th class="col-md-3"><%= t "team.created" %></th>
        <th class="col-md-1"><%= t ".edit" %></th>
        <th class="col-md-1"><%= t ".delete" %></th>
      </tr>
    </thead>
    <tbody>
      <% if organization.has_member? current_user %>
        <% teams.each_with_index do |team, index| %>
          <tr>
            <td class="col-md-2"><%= index + 1 %></td>
            <td class="col-md-3"><b><%= link_to team.name,
              [team.organization, team] %></b></td>
            <td class="col-md-3">
              <b><%= team.created_at.strftime("%b %d, %Y") %></b>
            </td>
            <% if team.has_admin? current_user %>
              <td class="col-md-1">
                <button class="btn btn-default">
                  <a href="<%= edit_organization_team_path(team.organization, team) %>">
                  <span class="fa fa-check"></span></a>
                </button>
              </td>
              <td class="col-md-1">
                  <button class="btn btn-default">
                  <%= link_to t("delete"), [team.organization, team],
                    method: :delete, data: {confirm: t("team.delete.delete")} %>
                    <span class="fa fa-ban"></span>
                  </button>
              </td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <% if organization.has_admin? current_user %>
    <div>
      <%= link_to t("team.new"), new_organization_team_path(organization) %>
    </div>
  <% end %>
</div>

app/views/organizations/show_tpl/_upload.html.erb
<div id="upload-modal" class="modal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="tittle text-center"><%= t ".upload_file" %></h4>
      </div>
      <div class="row modal-body">
        <div class="col-md-12">
          <%= form_for [@organization, @support.document],html: {multipart: true} do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control", required: "true",
              maxlength: Settings.document_length %>
            <%= f.label :description %>
            <%= f.text_area :description, placeholder:
              t(".compose_description"), class: "form-control", rows: Settings.rows %>
            <div class="row">
              <div class="col-md-12">
                <%= f.label :attachment %>
                <%= f.file_field :attachment %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6 category_doc_upload">
              <p><%= t ".category" %></p>
                <%= f.select :category_id, options_for_select(load_categories.collect{
                  |category| [category.name, category.id]}),
                  {class: "btn btn-default", include_blank: t(".all")}, required: true %>
              </div>
              <div class="col-md-6 serie_doc_upload">
                <p>
                  <b id="series-current"><%= t ".series" %></b>
                  <a id="create-series"><%= t ".create_serie" %></a>
                </p>
                <div id="create-series-area">
                  <input type="text" name="series_name" class="form-control">
                  <%= hidden_field_tag :organization_id, @organization.id %>
                </div>
                <div id="choose-series">
                  <%= f.select :serie_id, options_for_select(load_series(current_user, @organization.id).collect{
                    |serie| [serie.name, serie.id]}),
                    {class: "btn btn-default", include_blank: t(".all")} %>
                </div>
              </div>
            </div>
            <div class="row status_upload">
              <div class="col-md-12">
                <%= f.radio_button :status_upload, Settings.value_global, checked: true %>
                <%= f.label :status_upload, Settings.global, value: Settings.value_global %>
                <%= f.radio_button :status_upload, Settings.value_shared %>
                <%= f.label :status_upload, Settings.shared, value: Settings.value_shared %>
                <% if @organization.has_admin? current_user %>
                  <%= f.radio_button :status_upload, Settings.value_individual %>
                  <%= f.label :status_upload, Settings.individual,
                    value: Settings.value_individual %>
                <% end %>
              </div>
            </div>
            <div class="modal-footer">
              <%= f.submit t(".upload"), class: "btn btn-default" %>
              <button type="button" class="btn btn-default" data-dismiss="modal">
                <%= t ".close" %>
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>